Final deployment prep
TechForAutismDyslexia/imagematching pull request #2
Opened 2024-07-05 11:04 UTC by vaishnavikompella11

Fixes #1

2024-07-05 16:19 UTC, Jai-JAP commented
Rename all files returning react component to have `.jsx` extension

2024-07-05 16:21 UTC, Jai-JAP requested changes
Rename all files returning react component to have `.jsx` extension

2024-07-05 16:28 UTC, Jai-JAP requested changes
Move the assets folder from `/src/components/assets` to `/src/assets` and move `image.json` into the same.

2024-07-05 17:16 UTC, Jai-JAP approved these changes

2024-07-06 05:47 UTC, brohithkr approved these changes

2024-07-06 05:48 UTC, merged